name: On push Main

on:
  push:
    branches: [main]

jobs:
  build_csharp:
    runs-on: ubuntu-latest
    env:
      TEST_AUTH_TOKEN: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
      TEST_CACHE_NAME: client-sdk-csharp

    steps:
      - name: Get current time
        uses: gerred/actions/current-time@master
        id: current-time

      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Build
        run: |
          dotnet build
        shell: bash

      - name: Unit Test
        run: |
          dotnet test tests/Momento.Sdk.Tests/Unit
        shell: bash

      - name: Integration Test
        run: |
          dotnet test tests/Momento.Sdk.Tests/Integration
        shell: bash

      - name: Incubating Integration Test
        run: |
          dotnet test tests/Momento.Sdk.Incubating.Tests/Integration
        shell: bash

      - name: Set release
        id: semrel
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-initial-development-versions: true
          force-bump-patch-version: true

      - name: Pack and Publish
        run: |
          set -x
          pushd src/Momento.Sdk
            VERSION="${{ steps.semrel.outputs.version }}"
            echo "version: ${VERSION}"
            dotnet build --configuration Release
            dotnet pack -c Release -p:Version=${VERSION}
            dotnet nuget push ./bin/Release/Momento.Sdk.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key=${{secrets.NUGET_API_KEY}}
          popd
        shell: bash
