name: On push Main

on:
  push:
    branches: [main]

jobs:
  build_csharp:
    runs-on: ubuntu-latest
    env:
      TEST_AUTH_TOKEN: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
      TEST_CACHE_NAME: dummy

    steps:
      - name: Get current time
        uses: gerred/actions/current-time@master
        id: current-time

      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: "5.x"

      - name: Configure Artifactory publish credentials
        run: |
          set -e
          set -x
          nuget sources Add -Name Artifactory -Source https://momento.jfrog.io/artifactory/api/nuget/nuget-local -username deploy-user -password ${{ secrets.PUBLIC_ARTIFACTORY_DEPLOY_USER_MAGIC_PASSTOKEN }}
          nuget setapikey deploy-user:${{ secrets.PUBLIC_ARTIFACTORY_DEPLOY_USER_MAGIC_PASSTOKEN }} -Source Artifactory
          dotnet nuget add source https://momento.jfrog.io/artifactory/api/nuget/nuget-public --name Artifactory
        shell: bash

      - name: Build
        run: |
          dotnet build
        shell: bash

      - name: Unit Test
        run: |
          dotnet test MomentoTest
        shell: bash

      - name: Set release
        id: semrel
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-initial-development-versions: true
          force-bump-patch-version: true

      - name: Pack and Publish
        run: |
          set -x
          pushd Momento
            VERSION="${{ steps.semrel.outputs.version }}"
            echo "version: ${VERSION}"
            dotnet build --configuration Release
            dotnet pack -c Release -p:Version=${VERSION}
            nuget push ./bin/Release/MomentoSdk.${VERSION}.nupkg -Source Artifactory -Verbosity detailed
          popd
        shell: bash
