name: On pull request

on:
  pull_request:
    branches: [main]

jobs:
  build_csharp:
    runs-on: ubuntu-latest
    env:
      TEST_AUTH_TOKEN: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
      TEST_CACHE_NAME: client-sdk-csharp

    steps:
      - name: Get current time
        uses: gerred/actions/current-time@master
        id: current-time

      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Commitlint and Other Shared Build Steps
        uses: momentohq/standards-and-practices/github-actions/shared-build@gh-actions-v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          dotnet build
        shell: bash

      - name: Unit Test
        run: |
          dotnet test tests/Unit/Momento.Sdk.Tests
        shell: bash

      - name: Integration Test
        run: |
          dotnet test tests/Integration/Momento.Sdk.Tests
        shell: bash

      - name: Incubating Integration Test
        run: |
          dotnet test tests/Integration/Momento.Sdk.Incubating.Tests
        shell: bash

  build_examples:
    runs-on: ubuntu-latest
    env:
      # TODO: remove token stored as secret in favor of using a
      # momento-local instance that can be spun up for testing
      MOMENTO_AUTH_TOKEN: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Run samples
        id: validation
        continue-on-error: true
        run: |
          pushd dotnet/MomentoExamples
            dotnet build MomentoApplication
            dotnet run --project MomentoApplication
            dotnet build MomentoApplicationPresignedUrl
          popd
        shell: bash

      #- name: Send CI failure mail
      #  if: ${{ steps.validation.outcome == 'failure' }}
      #  uses: ./.github/actions/error-email-action
      #  with:
      #    username: ${{secrets.MAIL_USERNAME}}
      #    password: ${{secrets.MAIL_PASSWORD}}

      - name: Flag Job Failure
        if: ${{ steps.validation.outcome == 'failure' }}
        run: exit 1
