name: On pull request

on:
  pull_request:
    branches: [main]

jobs:
  build_csharp:
    runs-on: ubuntu-latest
    env:
      TEST_AUTH_TOKEN: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
      TEST_CACHE_NAME: dummy

    steps:
      - name: Get current time
        uses: gerred/actions/current-time@master
        id: current-time

      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: "5.x"

      - name: Configure Artifactory credentials
        run: |
          set -e
          set -x
          dotnet nuget add source https://momento.jfrog.io/artifactory/api/nuget/nuget-public --name Artifactory
        shell: bash

      - name: Build
        run: |
          dotnet build
        shell: bash

      - name: Unit Test
        run: |
          dotnet test MomentoTest
        shell: bash
